const LENGTH_VALIDATION = {
    NAME_MIN_LENGTH: 1,
    NAME_MAX_LENGTH: 50,
    NAME_MAX_LENGTH_IN_BULK_CREATION: 100,
    DESC_MAX_LENGTH: 2000,
    EMAIL_MIN_LENGTH: 1,
    EMAIL_MAX_LENGTH: 50,
    NUMBER_MAX_LENGTH: 16,
    PASSWORD_MAX_LENGTH: 128,
    PASSWORD_MIN_LENGTH: 8,
    FILTER_NAME_MIN: 2,
    FILTER_NAME_MAX: 50,
};

const TOKEN_EXPIRY_TIME = {
    ACCESS_TOKEN: 604800, // 15 mins:900 secs
    REMEMBERED_TOKEN: 2630000,
    INVITED_USER: 604800,//7 days
    RESET_PASSWORD: 604800,
    TEMP_TOKEN: 604800,
    DEFAULT: 900,
};

const APP_CONSTANTS = { MAX_ASSETS_ALLOWED_BEFORE_PAYMENT: 3 };

const META_CONSTANTS = { ID_FOR_REMOVE_SPEND: 922337203685478 };
const TRAINING_RULE_BUDGET_LIMIT = 3200;// 500;
export {
    LENGTH_VALIDATION,
    TOKEN_EXPIRY_TIME,
    APP_CONSTANTS,
    META_CONSTANTS,
    TRAINING_RULE_BUDGET_LIMIT
};

